app = "tailscaled"
kill_signal = "SIGINT"
kill_timeout = "5s"
primary_region = "nrt"

[deploy]
strategy = "immediate"

[env]
PORT = "41641"

[[services]]
internal_port = 41_641
processes = [ "app" ]
protocol = "udp"

  [services.concurrency]
  hard_limit = 100
  soft_limit = 75
  type = "connections"

  [[services.ports]]
  port = 41_641
